/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evidence_tools_digest_RDigester */

#ifndef _Included_com_evidence_tools_digest_RDigester
#define _Included_com_evidence_tools_digest_RDigester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    init
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_evidence_tools_digest_RDigester_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    update
 * Signature: (I[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_evidence_tools_digest_RDigester_update
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    finalHashHex
 * Signature: (I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_evidence_tools_digest_RDigester_finalChecksumHex
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
