/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evidence_tools_digest_RDigester */

#ifndef _Included_com_evidence_tools_digest_RDigester
#define _Included_com_evidence_tools_digest_RDigester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    init
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_evidence_tools_digest_RDigester_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    update
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_evidence_tools_digest_RDigester_update
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    finalHash
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_evidence_tools_digest_RDigester_finalHash
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_evidence_tools_digest_RDigester
 * Method:    finalHashHex
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_evidence_tools_digest_RDigester_finalHashHex
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
