/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evidence_tools_digest_RDigester_Algorithm */

#ifndef _Included_com_evidence_tools_digest_RDigester_Algorithm
#define _Included_com_evidence_tools_digest_RDigester_Algorithm
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
